apiVersion: v1
kind: Service
metadata:
  name: bitbucket-k8s
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: bitbucket-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitbucket-k8s
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: bitbucket-k8s
  template:
    metadata:
      labels:
        app: bitbucket-k8s
    spec:
      containers:
        - name: bitbucket-k8s
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
